BaseUrl = "http://fsharpshow.com"
LanguageCode = "en-us"
Title = "The F# Show"
disqusShortname = "fsharpshow"

[params]
  description = "A podcast dedicated to F#"
  summary = "A podcast dedicated to F#"
  hostsname = "Troy Kershaw"
  hostsurl = "http://troykershaw.com"
  hostsemail = "hello@troykershaw.com"
  email = "fsharpshow@troykershaw.com"
  cdnpath = "http://cdn.fsharpshow.com"
  twitterurl = "https://twitter.com/fsharpshow"
  itunesurl = "https://itunes.apple.com/podcast/the-f-show/id951577378"
  keywords = "F#,FSharp,.NET,functional,programming"
